### ISSUE TITLE
Add a "Focus Mode" that removes all headers/footers/branding

### ISSUE THREAD

**Issue by scottcate** [lbugnion/timekeeper#138]
getting feedback that the headers and footers cause scroll and distraction.

Focus mode would go full screen (inside the browser) and remove everything but what's critical.

Timers + notes sent to client.

**Comment by lbugnion** [comment]
Implemented in upcoming V0.6.2

![2021-06-25_12-04-51](https://user-images.githubusercontent.com/4922457/123408889-d5535980-d5ad-11eb-9feb-c5485c63548b.gif)
