### ISSUE TITLE
bind [ENTER] to post the message, same as the [Send Message] button click

### ISSUE THREAD

**Issue by scottcate** [lbugnion/timekeeper#75]
so the message can be sent from keyboard control.

[ENTER] = send message

then reset cursor back into empty message box for next message typing.

**Comment by lbugnion** [comment]
Also Select All when entering the Input Box would be nice.

Note to  the implementer: Might have to use JavaScript for this?

**Comment by lbugnion** [comment]
Implemented in V0.5.3.2
